// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employees.proto

#include "employees.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_employees_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_employees_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_employee;
}  // namespace protobuf_employees_2eproto
class employeeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<employee>
      _instance;
} _employee_default_instance_;
class employeesDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<employees>
      _instance;
} _employees_default_instance_;
namespace protobuf_employees_2eproto {
static void InitDefaultsemployee() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_employee_default_instance_;
    new (ptr) ::employee();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::employee::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_employee =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsemployee}, {}};

static void InitDefaultsemployees() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_employees_default_instance_;
    new (ptr) ::employees();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::employees::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_employees =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsemployees}, {
      &protobuf_employees_2eproto::scc_info_employee.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_employee.base);
  ::google::protobuf::internal::InitSCC(&scc_info_employees.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::employee, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::employee, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::employee, firstname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::employee, lastname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::employee, salary_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::employees, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::employees, employees_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::employee)},
  { 9, -1, sizeof(::employees)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_employee_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_employees_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "employees.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\017employees.proto\"K\n\010employee\022\n\n\002ID\030\001 \001("
      "\005\022\021\n\tFirstName\030\002 \001(\t\022\020\n\010LastName\030\003 \001(\t\022\016"
      "\n\006salary\030\004 \001(\002\")\n\temployees\022\034\n\temployees"
      "\030\003 \003(\0132\t.employeeb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 145);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "employees.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_employees_2eproto

// ===================================================================

void employee::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int employee::kIDFieldNumber;
const int employee::kFirstNameFieldNumber;
const int employee::kLastNameFieldNumber;
const int employee::kSalaryFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

employee::employee()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_employees_2eproto::scc_info_employee.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:employee)
}
employee::employee(const employee& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  firstname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.firstname().size() > 0) {
    firstname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.firstname_);
  }
  lastname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.lastname().size() > 0) {
    lastname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.lastname_);
  }
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&salary_) -
    reinterpret_cast<char*>(&id_)) + sizeof(salary_));
  // @@protoc_insertion_point(copy_constructor:employee)
}

void employee::SharedCtor() {
  firstname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  lastname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&salary_) -
      reinterpret_cast<char*>(&id_)) + sizeof(salary_));
}

employee::~employee() {
  // @@protoc_insertion_point(destructor:employee)
  SharedDtor();
}

void employee::SharedDtor() {
  firstname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  lastname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void employee::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* employee::descriptor() {
  ::protobuf_employees_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_employees_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const employee& employee::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_employees_2eproto::scc_info_employee.base);
  return *internal_default_instance();
}


void employee::Clear() {
// @@protoc_insertion_point(message_clear_start:employee)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  firstname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  lastname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&salary_) -
      reinterpret_cast<char*>(&id_)) + sizeof(salary_));
  _internal_metadata_.Clear();
}

bool employee::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:employee)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 ID = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string FirstName = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_firstname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->firstname().data(), static_cast<int>(this->firstname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "employee.FirstName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string LastName = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_lastname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->lastname().data(), static_cast<int>(this->lastname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "employee.LastName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float salary = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(37u /* 37 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &salary_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:employee)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:employee)
  return false;
#undef DO_
}

void employee::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:employee)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 ID = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // string FirstName = 2;
  if (this->firstname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->firstname().data(), static_cast<int>(this->firstname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "employee.FirstName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->firstname(), output);
  }

  // string LastName = 3;
  if (this->lastname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->lastname().data(), static_cast<int>(this->lastname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "employee.LastName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->lastname(), output);
  }

  // float salary = 4;
  if (this->salary() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->salary(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:employee)
}

::google::protobuf::uint8* employee::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:employee)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 ID = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // string FirstName = 2;
  if (this->firstname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->firstname().data(), static_cast<int>(this->firstname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "employee.FirstName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->firstname(), target);
  }

  // string LastName = 3;
  if (this->lastname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->lastname().data(), static_cast<int>(this->lastname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "employee.LastName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->lastname(), target);
  }

  // float salary = 4;
  if (this->salary() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->salary(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:employee)
  return target;
}

size_t employee::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:employee)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string FirstName = 2;
  if (this->firstname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->firstname());
  }

  // string LastName = 3;
  if (this->lastname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->lastname());
  }

  // int32 ID = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());
  }

  // float salary = 4;
  if (this->salary() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void employee::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:employee)
  GOOGLE_DCHECK_NE(&from, this);
  const employee* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const employee>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:employee)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:employee)
    MergeFrom(*source);
  }
}

void employee::MergeFrom(const employee& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:employee)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.firstname().size() > 0) {

    firstname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.firstname_);
  }
  if (from.lastname().size() > 0) {

    lastname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.lastname_);
  }
  if (from.id() != 0) {
    set_id(from.id());
  }
  if (from.salary() != 0) {
    set_salary(from.salary());
  }
}

void employee::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:employee)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void employee::CopyFrom(const employee& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:employee)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool employee::IsInitialized() const {
  return true;
}

void employee::Swap(employee* other) {
  if (other == this) return;
  InternalSwap(other);
}
void employee::InternalSwap(employee* other) {
  using std::swap;
  firstname_.Swap(&other->firstname_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  lastname_.Swap(&other->lastname_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(id_, other->id_);
  swap(salary_, other->salary_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata employee::GetMetadata() const {
  protobuf_employees_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_employees_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void employees::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int employees::kEmployeesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

employees::employees()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_employees_2eproto::scc_info_employees.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:employees)
}
employees::employees(const employees& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      employees_(from.employees_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:employees)
}

void employees::SharedCtor() {
}

employees::~employees() {
  // @@protoc_insertion_point(destructor:employees)
  SharedDtor();
}

void employees::SharedDtor() {
}

void employees::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* employees::descriptor() {
  ::protobuf_employees_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_employees_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const employees& employees::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_employees_2eproto::scc_info_employees.base);
  return *internal_default_instance();
}


void employees::Clear() {
// @@protoc_insertion_point(message_clear_start:employees)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  employees_.Clear();
  _internal_metadata_.Clear();
}

bool employees::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:employees)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .employee employees = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_employees()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:employees)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:employees)
  return false;
#undef DO_
}

void employees::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:employees)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .employee employees = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->employees_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3,
      this->employees(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:employees)
}

::google::protobuf::uint8* employees::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:employees)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .employee employees = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->employees_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->employees(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:employees)
  return target;
}

size_t employees::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:employees)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .employee employees = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->employees_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->employees(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void employees::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:employees)
  GOOGLE_DCHECK_NE(&from, this);
  const employees* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const employees>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:employees)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:employees)
    MergeFrom(*source);
  }
}

void employees::MergeFrom(const employees& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:employees)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  employees_.MergeFrom(from.employees_);
}

void employees::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:employees)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void employees::CopyFrom(const employees& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:employees)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool employees::IsInitialized() const {
  return true;
}

void employees::Swap(employees* other) {
  if (other == this) return;
  InternalSwap(other);
}
void employees::InternalSwap(employees* other) {
  using std::swap;
  CastToBase(&employees_)->InternalSwap(CastToBase(&other->employees_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata employees::GetMetadata() const {
  protobuf_employees_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_employees_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::employee* Arena::CreateMaybeMessage< ::employee >(Arena* arena) {
  return Arena::CreateInternal< ::employee >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::employees* Arena::CreateMaybeMessage< ::employees >(Arena* arena) {
  return Arena::CreateInternal< ::employees >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
