// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Actia.proto

#include "Actia.pb.h"
#include "Actia.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace Actia {

static const char* CheckIn_method_names[] = {
  "/Actia.CheckIn/GetFeature",
};

std::unique_ptr< CheckIn::Stub> CheckIn::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CheckIn::Stub> stub(new CheckIn::Stub(channel, options));
  return stub;
}

CheckIn::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetFeature_(CheckIn_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CheckIn::Stub::GetFeature(::grpc::ClientContext* context, const ::Actia::point& request, ::Actia::feature* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Actia::point, ::Actia::feature, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetFeature_, context, request, response);
}

void CheckIn::Stub::async::GetFeature(::grpc::ClientContext* context, const ::Actia::point* request, ::Actia::feature* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Actia::point, ::Actia::feature, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFeature_, context, request, response, std::move(f));
}

void CheckIn::Stub::async::GetFeature(::grpc::ClientContext* context, const ::Actia::point* request, ::Actia::feature* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFeature_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Actia::feature>* CheckIn::Stub::PrepareAsyncGetFeatureRaw(::grpc::ClientContext* context, const ::Actia::point& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Actia::feature, ::Actia::point, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetFeature_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Actia::feature>* CheckIn::Stub::AsyncGetFeatureRaw(::grpc::ClientContext* context, const ::Actia::point& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetFeatureRaw(context, request, cq);
  result->StartCall();
  return result;
}

CheckIn::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CheckIn_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CheckIn::Service, ::Actia::point, ::Actia::feature, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CheckIn::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Actia::point* req,
             ::Actia::feature* resp) {
               return service->GetFeature(ctx, req, resp);
             }, this)));
}

CheckIn::Service::~Service() {
}

::grpc::Status CheckIn::Service::GetFeature(::grpc::ServerContext* context, const ::Actia::point* request, ::Actia::feature* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Actia

