# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Actia.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x41\x63tia.proto\x12\x07\x65xample\" \n\x05Point\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03nom\x18\x02 \x01(\t\"\"\n\x07\x46\x65\x61ture\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03nom\x18\x02 \x01(\t2;\n\x07\x43heckIn\x12\x30\n\nGetFeature\x12\x0e.example.Point\x1a\x10.example.Feature\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Actia_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POINT']._serialized_start=24
  _globals['_POINT']._serialized_end=56
  _globals['_FEATURE']._serialized_start=58
  _globals['_FEATURE']._serialized_end=92
  _globals['_CHECKIN']._serialized_start=94
  _globals['_CHECKIN']._serialized_end=153
# @@protoc_insertion_point(module_scope)
